"""Added timestamps to project.

Revision ID: 9483e285de9d
Revises: 5bd4c3d6c1e4
Create Date: 2022-08-01 16:38:28.997266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9483e285de9d'
down_revision = '5bd4c3d6c1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('projects', sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'date_modified')
    op.drop_column('projects', 'date_created')
    # ### end Alembic commands ###
