"""Added pages.parent_id

Revision ID: c2f45eb88506
Revises: 9483e285de9d
Create Date: 2022-08-01 17:08:44.284105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f45eb88506'
down_revision = '9483e285de9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pages', 'pages', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_column('pages', 'parent_id')
    # ### end Alembic commands ###
